spring.application.name=second

#logging.pattern.console=%yellow(%d{HH:mm:ss.SS}) %blue(%-5level) %red([%thread]) %green(%logger{36}) %blue(:%line)

#now we have two dependencies, we have to tell the spring don't find any client
# I will tell at runtime which model to use
spring.ai.chat.client=false

spring.ai.openai.api-key=${OPEN_API_KEY}
spring.ai.openai.chat.options.model=${OPEN_AI_MODEL:gpt-5.4-nano}

spring.ai.google.gen-ai.api-key=${GEMINI_API_KEY}
spring.ai.gemini.chat.options.model=${GEMINI_AI_MODEL:gemini-2.5-flash-lite}
